# This workflow will do a clean install of node dependencies & build the source code on a Pull request to the Master branch.

name: Continuous Integration check for Docusaurus build

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: joatmon08/tech-portfolio
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies and static website
      run: |
        cd website
        yarn install
        yarn build
