# Checks whether the content in the pull request can be merged by running the checks

name: Continuous Integration

on: [pull_request]

jobs:
  build_docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          path: master
      - uses: actions/checkout@v2
        with:
          ref: sphinx
          path: sphinx
      - uses: actions/checkout@v2
        with:
          repository: rucio/rucio
          path: rucio
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r sphinx/requirements.sphinx.txt
      - name: Build docs
        run: |
          cd sphinx
          chmod 755 build-sphinx-docs.sh 
          ./build-sphinx-docs.sh
