name: Continuous Integration

on: [pull_request]

jobs:
  build_docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          path: master
      - uses: actions/checkout@v2
        with:
          ref: sphinx
          path: sphinx
      - uses: actions/checkout@v2
        with:
          repository: rucio/rucio
          path: rucio
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r sphinx/requirements.sphinx.txt
      - name: Build docs
        run: |
          cd sphinx
          chmod 755 build-sphinx-docs.sh 
          ./build-sphinx-docs.sh
      - name: Push content
        run: |
          cd master
          git init
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Push to Github Pages"

          remote_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          INPUT_BRANCH=${INPUT_BRANCH:-master}
          git push "${remote_repo}" HEAD:${INPUT_BRANCH} --follow-tags --force
       
