# This workflow will copy the files from Sphinx build repository to the Master branch.

name: Publish content to master repository

on:
  push:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "pip install -r requirements.sphinx.txt"
        build-command: "sphinx-build -b html . _build"
        docs-folder: "source/"

#Committing Documentation Changes

    - name: Commit documentation changes
      run: |
        git clone https://github.com/rucio/documentation.git --branch master --single-branch master
        cp -r source/_html/* master/website/static/rucio/
        cd website
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true

# Pushing changes into the Master branch

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
